-- Grant all privileges to tsuite user
ALTER USER tsuite WITH SUPERUSER CREATEDB CREATEROLE;
ALTER DATABASE tsuite_db OWNER TO tsuite;
ALTER SCHEMA public OWNER TO tsuite;
GRANT ALL PRIVILEGES ON DATABASE tsuite_db TO tsuite;
GRANT ALL PRIVILEGES ON SCHEMA public TO tsuite;
GRANT ALL ON ALL TABLES IN SCHEMA public TO tsuite;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO tsuite;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO tsuite;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO tsuite;
